  export const reservations = [
    { 
      id: 1, 
      tipo: "Quadra de Tênis", 
      data: "15 Nov 2025", 
      hora: "15:00",
      horaInicio: "15:00",
      horaTermino: "17:00",
      ref: "RES-2025-001",
      participants: 4,
      paymentMethod: "Cartão",
      description: "Treino semanal de tênis",
      decoracaoInterna: false,
      cateringInterno: true,
      djInterno: false,
      decoracaoExterna: false,
      cateringExterno: false,
      djExterno: false,
      contactoDecoradora: "",
      contactoCatering: "catering@exemplo.com",
      contactoDJ: "",
      outrasInformacoes: "Trazer raquetes próprias",
      assinaturaFuncionario: "João Silva",
      comProducao: false,
      diasProducao: 0,
      status: "confirmada" as const,
      pagamentos: [
        { id: 'p1', dataVencimento: "15 Nov 2025", valor: 500, status: "pago" as const },
        { id: 'p2', dataVencimento: "30 Nov 2025", valor: 500, status: "pago" as const },
        { id: 'p3', dataVencimento: "15 Dez 2025", valor: 500, status: "pago" as const }
      ],
      total: 1500,
      totalPago: 1500,
      saldoPendente: 0,
      paymentStatus: "PAGO" as const,
      caucao: { valor: 200, status: "pago" as const, dataPagamento: "14 Nov 2025" }
    },
    { 
      id: 2, 
      tipo: "Sala de Conferência", 
      data: "18 Nov 2025", 
      hora: "10:00",
      horaInicio: "10:00",
      horaTermino: "12:00",
      ref: "RES-2025-002",
      participants: 10,
      paymentMethod: "Transferência",
      description: "Reunião corporativa",
      decoracaoInterna: true,
      cateringInterno: false,
      djInterno: false,
      decoracaoExterna: false,
      cateringExterno: true,
      djExterno: false,
      contactoDecoradora: "decor@exemplo.com",
      contactoCatering: "",
      contactoDJ: "",
      outrasInformacoes: "Projetor necessário",
      assinaturaFuncionario: "Maria Santos",
      comProducao: true,
      diasProducao: 2,
      status: "pendente" as const,
      pagamentos: [
        { id: 'p4', dataVencimento: "18 Nov 2025", valor: 450, status: "pago" as const },
        { id: 'p5', dataVencimento: "02 Dez 2025", valor: 450, status: "pendente" as const }
      ],
      total: 900,
      totalPago: 450,
      saldoPendente: 450,
      paymentStatus: "PARCIAL" as const,
      caucao: { valor: 100, status: "pendente" as const, dataPagamento: "" }
    },
    { 
      id: 3, 
      tipo: "Espaço para Eventos", 
      data: "22 Nov 2025", 
      hora: "18:00",
      horaInicio: "18:00",
      horaTermino: "22:00",
      ref: "RES-2025-003",
      participants: 50,
      paymentMethod: "Dinheiro",
      description: "Festa de aniversário",
      decoracaoInterna: true,
      cateringInterno: true,
      djInterno: true,
      decoracaoExterna: true,
      cateringExterno: false,
      djExterno: false,
      contactoDecoradora: "decor1@exemplo.com",
      contactoCatering: "catering1@exemplo.com",
      contactoDJ: "dj@exemplo.com",
      outrasInformacoes: "Música ao vivo opcional",
      assinaturaFuncionario: "Pedro Oliveira",
      comProducao: false,
      diasProducao: 0,
      status: "confirmada" as const,
      pagamentos: [
        { id: 'p6', dataVencimento: "22 Nov 2025", valor: 500, status: "pago" as const },
        { id: 'p7', dataVencimento: "06 Dez 2025", valor: 500, status: "pago" as const },
        { id: 'p8', dataVencimento: "20 Dez 2025", valor: 500, status: "pendente" as const },
        { id: 'p9', dataVencimento: "03 Jan 2026", valor: 500, status: "pendente" as const }
      ],
      total: 2000,
      totalPago: 1000,
      saldoPendente: 1000,
      paymentStatus: "PARCIAL" as const,
      caucao: { valor: 300, status: "pago" as const, dataPagamento: "21 Nov 2025" }
    }
  ];
  
  export const desportoSessions = [
    { 
      id: 1, 
      tipo: "Aula de Futsal", 
      data: "12 Nov 2025", 
      hora: "19:00",
      nomeEquipe: "Futsal Stars",
      email: "futsal@equipe.com",
      morada: "Rua das Flores, 123",
      bi: "123456789",
      nomeResponsavel: "Carlos Mendes",
      contato: "+244 912 345 678",
      diasSemana: ["Segunda", "Quarta", "Sexta"],
      horarioInicio: "19:00",
      horarioFim: "21:00",
      tipoAtividade: "Futsal",
      corIdentificacao: "#FF0000",
      valorPagamento: 600,
      modalidadePagamento: "Mensal",
      tipoPeriodo: "Semanal",
      vendaIngresso: "Sim",
      valorIngresso: 50,
      valorCaucao: 150,
      dataInicio: new Date("2025-11-01"),
      dataFim: new Date("2025-12-31"),
      situacao: "Ativa",
      campo: "Campo Principal",
      statusPagamento: "Pago",
      observacoesAdicionais: "Treino intensivo",
      valorPago: 600,
      valorPendente: 0,
      ultimoPagamento: new Date("2025-11-01"),
      status: "confirmada" as const,
      instrutor: "João Silva",
      pagamentos: [
        { id: 'd1', dataVencimento: "12 Nov 2025", valor: 300, status: "pago" as const },
        { id: 'd2', dataVencimento: "26 Nov 2025", valor: 300, status: "pago" as const }
      ],
      total: 600,
      caucao: { valor: 150, status: "pago" as const, dataPagamento: "11 Nov 2025" }
    },
    { 
      id: 2, 
      tipo: "Treino de Tênis", 
      data: "16 Nov 2025", 
      hora: "17:00",
      nomeEquipe: "Tênis Elite",
      email: "tenis@equipe.com",
      morada: "Av. Principal, 456",
      bi: "987654321",
      nomeResponsavel: "Ana Costa",
      contato: "+244 923 456 789",
      diasSemana: ["Terça", "Quinta"],
      horarioInicio: "17:00",
      horarioFim: "19:00",
      tipoAtividade: "Tênis",
      corIdentificacao: "#00FF00",
      valorPagamento: 800,
      modalidadePagamento: "Semanal",
      tipoPeriodo: "Mensal",
      vendaIngresso: "Não",
      valorIngresso: 0,
      valorCaucao: 200,
      dataInicio: new Date("2025-11-01"),
      dataFim: null,
      situacao: "Pendente",
      campo: "Quadra 1",
      statusPagamento: "Parcial",
      observacoesAdicionais: "Aula para iniciantes",
      valorPago: 0,
      valorPendente: 800,
      ultimoPagamento: null,
      status: "pendente" as const,
      instrutor: "Maria Santos",
      pagamentos: [
        { id: 'd3', dataVencimento: "16 Nov 2025", valor: 400, status: "pendente" as const },
        { id: 'd4', dataVencimento: "30 Nov 2025", valor: 400, status: "pendente" as const }
      ],
      total: 800,
      caucao: { valor: 200, status: "pendente" as const, dataPagamento: "" }
    },
    { 
      id: 3, 
      tipo: "Grupo de Natação", 
      data: "20 Nov 2025", 
      hora: "16:00",
      nomeEquipe: "Nado Livre",
      email: "nado@equipe.com",
      morada: "Rua das Ondas, 789",
      bi: "456789123",
      nomeResponsavel: "Pedro Lima",
      contato: "+244 934 567 890",
      diasSemana: ["Quarta", "Sábado"],
      horarioInicio: "16:00",
      horarioFim: "17:30",
      tipoAtividade: "Natação",
      corIdentificacao: "#0000FF",
      valorPagamento: 250,
      modalidadePagamento: "Trimestral",
      tipoPeriodo: "Semanal",
      vendaIngresso: "Sim",
      valorIngresso: 20,
      valorCaucao: 100,
      dataInicio: new Date("2025-11-01"),
      dataFim: new Date("2025-11-30"),
      situacao: "Cancelada",
      campo: "Piscina Principal",
      statusPagamento: "Pago",
      observacoesAdicionais: "Grupo cancelado por baixa adesão",
      valorPago: 250,
      valorPendente: 0,
      ultimoPagamento: new Date("2025-11-01"),
      status: "cancelada" as const,
      instrutor: "Pedro Oliveira",
      pagamentos: [
        { id: 'd5', dataVencimento: "20 Nov 2025", valor: 250, status: "pago" as const }
      ],
      total: 250,
      caucao: { valor: 100, status: "devolvido" as const, dataPagamento: "19 Nov 2025" }
    }
  ];
  
  export const gymSessions = [
    { 
      id: 1, 
      data: "10 Nov 2025", 
      duracao: "1h 30min", 
      tipo: "Musculação",
      status: "presente" as const,
      horaEntrada: "08:00",
      horaSaida: "09:30",
      actividade: "Treino de força",
      observacoes: "Bom desempenho",
      consumos: [
        { id: 'c1', produto: "Água 500ml", quantidade: 1, valorTotal: 50, pago: true, metodoPagamento: "Cartão", observacoes: "" }
      ]
    },
    { 
      id: 2, 
      data: "08 Nov 2025", 
      duracao: "1h", 
      tipo: "Cardio",
      status: "ausente" as const,
      horaEntrada: "18:00",
      horaSaida: "",
      actividade: "Esteira",
      observacoes: "Ausente justificado",
      consumos: []
    },
    { 
      id: 3, 
      data: "05 Nov 2025", 
      duracao: "2h", 
      tipo: "Funcional",
      status: "justificado" as const,
      horaEntrada: "07:00",
      horaSaida: "09:00",
      actividade: "Circuito completo",
      observacoes: "Feriado",
      consumos: [
        { id: 'c2', produto: "Shake Proteína", quantidade: 1, valorTotal: 200, pago: false, metodoPagamento: "", observacoes: "Cobrar próximo" }
      ]
    }
  ];